name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: run debug unit tests
      run: ./gradlew testDebugUnitTest
    
    - name: build with gradle
      run: ./gradlew build
    
    - name: upload apk
      uses: actions/upload-artifact@v1.0.0
      with:
        name: AndroidPractice Debug APK
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: upload debug unit test report
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Debug Unit Test Report
        path: app/build/reports/tests/testDebugUnitTest
